### PR TITLE
Issue 21 Can't interrupt blocking accept

### PR DESCRIPTION
**Pull request by gregw**
This is an attempted fix for #21 
It does make it a little better as the testAcceptCloseInterrupt() test now sometimes passes (1 in 5 runs on my machine), but it has not fixed the problem generally.

Probably not worthwhile merging, just wanted to move #21 on.

### CODE REVIEW

**Comment by headius** [comment]
Sorry this got left on the shelf so long. I submitted a review that needs some changes.

**Comment by gregw** [comment]
@headius formatting was fixed some time ago.   I've just merged from master to freshen this up.
No idea yet why CI is failing.... but I think this is a needed change (now duplicated by #52)

**Comment by gregw** [comment]
@headius can you re-review this one?

**Comment by gregw** [comment]
@headius actually this is now not working reliably... so the fix is not good... but the issue is important

**Comment by headius** [comment]
@gregw Sorry for dropping the ball on this but thank you for the update. I'll close this and we'll look at another fix.

**Pull request closed without merging**
