### PR TITLE
Run the example via Maven.

### PR DESCRIPTION
**Pull request by alxn**
My Maven-foo is not the best, but it manages to run the example server+client as part of `mvn install`.

### CODE REVIEW

**Comment by headius** [comment]
I kicked the build to see if it would go green now. If you can help us green up, I'd love to merge this. At least we'd have some sort of testing then :-)

**Comment by alxn** [comment]
@headius sure, just rebasing and I'll see what's wrong.

**Comment by alxn** [comment]
@headius Green tick achieved.

**Comment by alxn** [comment]
@headius green tick achieved - ping.

**Pull request merged**
