### PR TITLE
Fix #60 (calling close on a UnixSocket with a pending read waits for the read to time out on Linux)

### LINKED ISSUE #60: Calling close on a UnixSocket with a pending read waits for the read to time out on Linux
If you create a `UnixSocket`, set a read timeout and then:

* call `read()` on one thread
* wait a bit and then call `close()` on another thread

...the behaviour is different on OS X and Linux.

On OS X, the read is cancelled as soon as `close()` is called and so `close()` returns immediately. On Linux, the read blocks until the read timeout is reached, and then `close()` returns. 

This makes interrupting read operations impossible, and is the root cause of https://github.com/square/okhttp/issues/4233.

I have created a test case that fails on Linux (but passes on OS X) in https://github.com/charleskorn/jnr-unixsocket/commit/b0981aeb2001fd5367ecceba954106c00e337497.

### PR DESCRIPTION
**Pull request by charleskorn**
See #60 for details.

### CODE REVIEW

**Comment by charleskorn** [comment]
I have tested this on both Linux and OS X, this change may reveal other issues on other OSes.

**Comment by rhuss** [comment]
Any chance to get this PR merged and getting a new release ?

**Comment by rhuss** [comment]
@headius Is there anything I can help to get a release with this fix included? It looks like that this PR fixes are long outstanding (and difficult) [bug in d-m-p](https://github.com/fabric8io/docker-maven-plugin/issues/552) when accessing the same socket from multiple threads. Unfortunately I'm not deep enough in the weeds to make a qualified review for this PR but I got reports that this will indeed fix that prio1 bug over there in d-m-p land.

Happy new year btw ;-)

**Comment by headius** [comment]
Sorry about delays...cycling back through JNR stuff now!

**Comment by headius** [comment]
I'll push out a release today!

**Comment by rhuss** [comment]
@headius awesome, thanks a ton !

**Pull request merged**
